name: Deploy-NextJS
on: [push]
jobs:
  deploy-nextjs_app:
    runs-on: self-hosted   
    steps:
      - name: Magicking 😀
        shell: bash
        run: |
          cd ~
          cd /var/www/html/multiapp-cicd/nextjs-app
          sudo chown -R pundir:pundir /var/www/html/multiapp-cicd/nextjs-app 
      - name: Install Dependencies
        shell: bash
        run: |
          cd /var/www/html/multiapp-cicd/nextjs-app
          npm install
      - name: Lint
        shell: bash
        run: |
          cd /var/www/html/multiapp-cicd/nextjs-app
          npm run lint
      - name: Test
        shell: bash
        run: |
          cd /var/www/html/multiapp-cicd/nextjs-app
          npm run test
