name: Deploy-Wordpress
on:
  push:
    paths:
      - 'wordpress-app/**'
jobs:
  deploy-wordpress_app:
    runs-on: self-hosted   
    steps:
      - name: Magicking 😀
        shell: bash
        run: |
          cd ~
          cd /var/www/html/multiapp-cicd/wordpress-app
          sudo chown -R pundir:pundir /var/www/html/multiapp-cicd/wordpress-app 
      - name: Install Dependencies
        shell: bash
        run: |
          cd /var/www/html/multiapp-cicd/wordpress-app
          sudo apt install composer
          sudo composer install
      - name: PHPCS
        shell: bash
        run: |
          cd /var/www/html/multiapp-cicd/wordpress-app
          sudo composer phpcs
